version: 2.1

orbs:
  renovate: daniel-shuy/renovate@x.y

workflows:
  lint: 
    jobs: 
      -renovate/validate-config
  renovate:
    jobs:
      - renovate/self-hosted:
          config_file_path: renovate.json
    nightly:
      triggers:
        - schedule:
            cron: 0 0 * * *
            filters:
              branches:
                only:
                  - main
